<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tyuiu.ZipunovIM.Sprint1.Task3.V12_Lib</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="tyuiu.cources.programming.interfaces">
      <HintPath>..\..\..\..\Desktop\tyuiu.cources.programming.interfaces-main\tyuiu.cources.programming.interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
