<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.ZipunovIM.Sprint1.Task2.V1.Lib\Tyuiu.ZipunovIM.Sprint1.Task2.V1.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="tyuiu.cources.programming.interfaces">
      <HintPath>..\..\..\..\Desktop\tyuiu.cources.programming.interfaces-main\tyuiu.cources.programming.interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
